### ISSUE TITLE
Ссылка на объект не нужна

### ISSUE THREAD

**Issue by altolstikhin** [Andrew-coder911/OOPLessonTest#1]
Ссылка на объект не нужна, тк она есть в другом классе

https://github.com/Andrew-coder911/OOPLessonTest/blob/9d7f92ee7a5693ad90bed57ce3f7abc953b2b724/src/com/github/andrewcoder/Home.java#L6

**Comment by Andrew-coder911** [comment]
Внес исправления в проект. Удалены лишние ссылки, отредактирован вывод, удалены лишние сеттеры, настроены конструкторы.
