### ISSUE TITLE
Одинаковые ссылки в homeRunner

### ISSUE THREAD

**Issue by altolstikhin** [Andrew-coder911/OOPLessonTest#3]
Room room1 = new Room(true);
        Room room2 = new Room(false);
        Room[] rooms = {room1, room2};

        Flat flat = new Flat(194,rooms);
        Flat flat1 = new Flat(129, rooms);

Сделай два разных набора rooms для разный flat.

Так же сделай с остальными объектами, которые создаёшь в том методе.

**Comment by Andrew-coder911** [comment]
Исправлено в текущем коммите.
